databases:
  - name: sihati
    databaseName: sihati
    user: sihati_user

services:
  - type: web
    name: sihati_services
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sihati
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
